# Generated by Django 5.0 on 2024-01-02 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0002_order_city_order_completed_at_order_is_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='paystack_reference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
