# Generated by Django 5.0 on 2024-01-06 16:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_merchant', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('address', models.TextField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'CustomUser',
            },
        ),
        migrations.CreateModel(
            name='SellerProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=100)),
                ('business_reg_no', models.CharField(blank=True, max_length=100, null=True)),
                ('business_cert', models.FileField(blank=True, null=True, upload_to='business_cert/')),
                ('business_address', models.CharField(blank=True, max_length=100, null=True)),
                ('business_address_proof', models.FileField(blank=True, null=True, upload_to='business_address_proof/')),
                ('business_type', models.CharField(choices=[('sole proprietorship', 'Sole Proprietorship'), ('limited liability company', 'Limited Liability Company'), ('corporation', 'Corporation'), ('partnership', 'Partnership'), ('professional corporation', 'Professional Corporation'), ('cooperative', 'Cooperative')], default='sole proprietorship', max_length=100)),
                ('is_seller_accept_terms', models.BooleanField(default=False)),
                ('nin_number', models.CharField(max_length=100, null=True)),
                ('nin_card', models.FileField(null=True, upload_to='nin_card/')),
                ('nin_selfie', models.FileField(null=True, upload_to='nin_selfie/')),
                ('account_name', models.CharField(max_length=100, null=True)),
                ('bank_name', models.CharField(max_length=100, null=True)),
                ('account_number', models.IntegerField(null=True)),
                ('is_return_refund_accept', models.BooleanField(default=False)),
                ('is_warranty', models.BooleanField(blank=True, default=False, null=True)),
                ('warranty_duration', models.IntegerField(blank=True, null=True)),
                ('business_logo', models.ImageField(blank=True, null=True, upload_to='business_logo/')),
                ('profile_picture', models.ImageField(null=True, upload_to='profile_pictures/')),
                ('personal_address', models.CharField(max_length=100, null=True)),
                ('personal_address_proof', models.FileField(null=True, upload_to='personal_address_proof/')),
                ('business_bio', models.TextField(max_length=255, null=True)),
                ('is_platform_policy_accept', models.BooleanField(default=False)),
                ('is_use_verify_info', models.BooleanField(default=False)),
                ('business_license', models.FileField(blank=True, null=True, upload_to='business_licenses/')),
                ('is_verified', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
