# Generated by Django 5.0 on 2024-01-13 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerprofile',
            name='business_type',
            field=models.CharField(blank=True, choices=[('sole proprietorship', 'Sole Proprietorship'), ('limited liability company', 'Limited Liability Company'), ('corporation', 'Corporation'), ('partnership', 'Partnership'), ('professional corporation', 'Professional Corporation'), ('cooperative', 'Cooperative')], default='sole proprietorship', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sellerprofile',
            name='is_return_refund_accept',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='sellerprofile',
            name='nin_card',
            field=models.FileField(blank=True, null=True, upload_to='nin_card/'),
        ),
        migrations.AlterField(
            model_name='sellerprofile',
            name='nin_selfie',
            field=models.FileField(blank=True, null=True, upload_to='nin_selfie/'),
        ),
        migrations.AlterField(
            model_name='sellerprofile',
            name='personal_address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sellerprofile',
            name='personal_address_proof',
            field=models.FileField(blank=True, null=True, upload_to='personal_address_proof/'),
        ),
    ]
