# Generated by Django 5.0 on 2024-01-14 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_alter_sellerprofile_business_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerprofile',
            name='account_number',
            field=models.IntegerField(max_length=25555, null=True),
        ),
    ]
