# Generated by Django 5.0 on 2024-01-14 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0003_alter_sellerprofile_account_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerprofile',
            name='account_number',
            field=models.PositiveBigIntegerField(null=True),
        ),
    ]
