# Generated by Django 5.0 on 2023-12-30 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Whishlist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite',
            name='is_favourite',
            field=models.BooleanField(default=False),
        ),
    ]
